server:
  port: 8888
spring:
  datasource:
    username: xxx
    password: xxx
    url: jdbc:mysql://xxxx:3306/coolschooldb?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:generator/*.xml
  type-aliases-package: com.myappbbsbackend.test.entity

---
#server:
#  port: 8888
#spring:
#  datasource:
#    username: root
#    password: admin
#    url: jdbc:mysql://localhost:3306/coolschooldb?serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#mybatis:
#  mapper-locations: classpath:generator/*.xml
#  type-aliases-package: com.myappbbsbackend.test.entity


